"""empty message

Revision ID: 85313735e92f
Revises: 
Create Date: 2024-01-27 09:46:51.718466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85313735e92f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('news', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
